CREATE TABLE ACCOUNT
(
  ID bigint NOT NULL,
  ACCOUNT_ID bigint,
  ACCOUNT_NAME varchar(50),
  ACCOUNT_TYPE bigint,
  IS_ACTIVE bit(1),
  USER_ID bigint,
  BALANCE_AMOUNT bigint,
  CREATE_DATE timestamp,
  UPDATE_DATE timestamp,
  CREATE_BY bigint,
  UPDATED_BY bigint,
  CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT_TYPE
(
  ID bigint NOT NULL,
  ACCOUNT_DESC varchar(10),
  ACCOUNT_TYPE varchar(25),
  CONSTRAINT PK_ACCOUNT_TYPE PRIMARY KEY (ID)
);

CREATE TABLE ROLE
(
  ID bigint NOT NULL,
  ROLE varchar(50),
  DESCRIPTION varchar(100),
  CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTION_SUMMARY
(
  ID bigint NOT NULL,
  SRC_ACCOUNT_ID bigint,
  DEST_ACCOUNT_ID bigint,
  CREATE_DATE timestamp,
  UPDATE_DATE timestamp,
  TRANSFER_REF_NO varchar(20),
  TRANSFER_AMOUNT decimal(10,5),
  USER_ID bigint,
  IS_COMPLETE bool,
  CONSTRAINT PK_TRANSACTION_SUMMARY PRIMARY KEY (ID)
);

CREATE TABLE USER
(
  ID bigint NOT NULL,
  USER_NAME varchar(50),
  FIRST_NAME varchar(100),
  LAST_NAME varchar(100),
  IS_ACTIVE bigint,
  BIRTH_DATE date,
  ADDRESS_LINE1 varchar(200),
  POSTAL_CODE varchar(20),
  COUNTRY varchar(50),
  GENDER varchar(5),
  EMAIL_ID varchar(50),
  PRIMARY_MOBILE_NO varchar(15),
  SECONDRY_MOBILE_NO varchar(15),
  CREATE_DATE timestamp,
  UPDATE_DATE timestamp,
  CREATE_BY bigint,
  UPDATED_BY bigint,
  CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE
(
  ID bigint NOT NULL,
  USER_ID bigint,
  ROLE_ID bigint,
  CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID)
);

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_TYPE (ID);

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USER
  FOREIGN KEY (USER_ID) REFERENCES USER (ID);

ALTER TABLE TRANSACTION_SUMMARY ADD CONSTRAINT FK_TRANSACTION_SUMMARY_
  FOREIGN KEY (SRC_ACCOUNT_ID) REFERENCES ACCOUNT (ID);

ALTER TABLE TRANSACTION_SUMMARY ADD CONSTRAINT FK_TRANSACTION_SUMMARY_DEST
  FOREIGN KEY (DEST_ACCOUNT_ID) REFERENCES ACCOUNT (ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_
  FOREIGN KEY (USER_ID) REFERENCES USER (ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);